name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for deploying to GitHub Pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true # Fetch Hugo themes

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          # hugo-version: "latest"
          hugo-version: "0.139.4" # 2024/12/22現在、最新版v0.139.5で404エラーが発生してしまうため、手動でバージョンを下げている ref: https://github.com/peaceiris/actions-hugo/issues/652
          extended: true # Use Hugo extended version

      - name: Build Hugo site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
